# Generated by Django 3.0.1 on 2019-12-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_college_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.College'),
        ),
    ]
