# Generated by Django 3.0.1 on 2019-12-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_student_clg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
